[package]
name = "day23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-utils = { path = "../../aoc-utils" }
graphviz-rust = "0.9.3"
lazy-regex = "3.3.0"
